Repository uber-workflow/probot-app-merge-pr, pull requests merged in 2019-01, with the labels that each got.

#78 Migrate to async/await for ease of bypassing caught exceptions
  __tests__/index.js
  index.js
Labels: refactor

#77 Update squash commit message to include all PR commit authors
  LICENSE
  __tests__/__fixtures__/issue_comment.created.js
  __tests__/__fixtures__/listCommits.js
  __tests__/__fixtures__/reviewUserPermissionLevel.js
  __tests__/index.js
  index.js
  package.json
  yarn.lock
Labels: feature

#79 Release v1.1.0
  package.json
Labels: release
